# Use root/example as user/password credentials

version: '3'
services:
  db:
    image: mongo:5
    restart: always
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo:/data/db
    environment:
      - MONGODB_DATABASENAME=nest-pokemon
